FROM rust:1-trixie as build

ENV CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc \
    AR_aarch64_unknown_linux_gnu=aarch64-linux-gnu-ar \
    CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc \
    CXX_aarch64_unknown_linux_gnu=aarch64-linux-gnu-g++ 

ENV PKG_CONFIG_ALLOW_CROSS=1
ENV PKG_CONFIG_PATH="/usr/lib/aarch64-linux-gnu/pkgconfig/:${PKG_CONFIG_PATH}"


RUN dpkg --add-architecture arm64
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -qq install just g++-aarch64-linux-gnu libc6-dev-arm64-cross libglib2.0-dev:arm64 

WORKDIR /app
RUN rustup target add aarch64-unknown-linux-gnu
RUN rustup toolchain install --force-non-host stable-aarch64-unknown-linux-gnu

RUN cargo install sqlx-cli

RUN DEBIAN_FRONTEND=noninteractive apt-get -qq install libssl-dev:arm64 libasound2-dev:arm64 # curl nodejs npm

COPY macos-module macos-module
COPY gtk-module gtk-module
COPY disconnect-module disconnect-module
COPY disconnect-server-module disconnect-server-module
COPY mpris-module mpris-module
COPY rfid-module rfid-module
COPY controls-module controls-module
COPY cli-module cli-module
COPY gpio-module gpio-module
COPY qobuz-client qobuz-client
COPY qconnect-protocol qconnect-protocol
COPY qconnect-transport-ws  qconnect-transport-ws
COPY player-module player-module
COPY connect-module connect-module
COPY tui-module tui-module
COPY web-module web-module
COPY justfile ./
COPY Cargo.toml ./
# COPY Cargo.lock ./
# COPY cargo-sources.json ./
# COPY codebook.toml ./

ENV targ=aarch64-unknown-linux-gnu
RUN just create-env-file && just init-database

RUN cargo build -j 6 -p connect-module -p tui-module -p web-module --release --features connect --target=$targ

RUN mv target/aarch64-unknown-linux-gnu/release/qobine-web . 
RUN mv target/aarch64-unknown-linux-gnu/release/qobine-tui . 
RUN mv target/aarch64-unknown-linux-gnu/release/qobine-connect . 
